function tests = test_ardupilot_default_json_config
%TEST_ARDUPILOT_DEFAULT_JSON_CONFIG Проверки типовой конфигурации TASK-12.
% Назначение:
%   Подтверждает, что функция `uav.ardupilot.default_json_config`
%   возвращает структуру с обязательными полями для обмена по `JSON`
%   и `UDP`, а также с параметрами подготовки `ArduPilot SITL`.

tests = functiontests(localfunctions);
end

function setupOnce(~)
%SETUPONCE Подключить исходный код проекта.

repoRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(repoRoot, 'src'));
end

function testDefaultConfigContainsRequiredFields(testCase)
%TESTDEFAULTCONFIGCONTAINSREQUIREDFIELDS Проверить состав полей.

cfg = uav.ardupilot.default_json_config();

required_fields = { ...
    'udp_local_ip', ...
    'udp_local_port', ...
    'udp_remote_ip', ...
    'udp_remote_port', ...
    'frame_type', ...
    'motor_count', ...
    'pwm_min_us', ...
    'pwm_max_us', ...
    'pwm_hover_us', ...
    'motor_order', ...
    'update_rate_hz', ...
    'use_ardupilot_json', ...
    'ardupilot_root', ...
    'wsl_distro_name', ...
    'sitl_vehicle', ...
    'sitl_frame', ...
    'sitl_start_timeout_s', ...
    'udp_handshake_timeout_s', ...
    'expected_servo_channels', ...
    'tools_windows_dir', ...
    'tools_wsl_dir', ...
    'matlab_wait_for_packet_script', ...
    'matlab_handshake_script', ...
    'notes'};

for k = 1:numel(required_fields)
    field_name = required_fields{k};
    verifyTrue(testCase, isfield(cfg, field_name));
end

verifyEqual(testCase, cfg.motor_count, 4);
verifyEqual(testCase, numel(cfg.motor_order), cfg.motor_count);
verifyGreaterThan(testCase, cfg.pwm_max_us, cfg.pwm_min_us);
verifyTrue(testCase, logical(cfg.use_ardupilot_json));
verifyGreaterThan(testCase, cfg.expected_servo_channels, 0);
verifyGreaterThan(testCase, strlength(cfg.wsl_distro_name), 0);
verifyGreaterThan(testCase, strlength(cfg.ardupilot_root), 0);
end
