function tests = test_ground_station_install_scripts
%TEST_GROUND_STATION_INSTALL_SCRIPTS Проверки сценариев установки наземных станций.
% Назначение:
%   Подтверждает наличие PowerShell-сценариев проверки и безопасной
%   установки Mission Planner и QGroundControl.

tests = functiontests(localfunctions);
end

function testInstallScriptsExistAndExposeExecute(testCase)
%TESTINSTALLSCRIPTSEXISTANDEXPOSEEXECUTE Проверить наличие файлов и -Execute.

repoRoot = fileparts(fileparts(mfilename('fullpath')));
missionPlannerPath = fullfile( ...
    repoRoot, ...
    'tools', ...
    'ardupilot', ...
    'windows', ...
    'Install-MissionPlanner.ps1');
qgcPath = fullfile( ...
    repoRoot, ...
    'tools', ...
    'ardupilot', ...
    'windows', ...
    'Install-QGroundControl.ps1');

verifyTrue(testCase, isfile(missionPlannerPath));
verifyTrue(testCase, isfile(qgcPath));

missionPlannerText = fileread(missionPlannerPath);
qgcText = fileread(qgcPath);

verifyTrue(testCase, contains(missionPlannerText, '[switch]$Execute'));
verifyTrue(testCase, contains(qgcText, '[switch]$Execute'));
verifyTrue(testCase, contains(missionPlannerText, 'MissionPlanner-latest.msi'));
verifyTrue(testCase, contains(qgcText, 'https://github.com/mavlink/qgroundcontrol/releases/latest'));
end

function testInstallScriptsDefaultToSafeMode(testCase)
%TESTINSTALLSCRIPTSDEFAULTTOSAFEMODE Проверить наличие безопасного режима.

repoRoot = fileparts(fileparts(mfilename('fullpath')));
missionPlannerText = fileread(fullfile( ...
    repoRoot, ...
    'tools', ...
    'ardupilot', ...
    'windows', ...
    'Install-MissionPlanner.ps1'));
qgcText = fileread(fullfile( ...
    repoRoot, ...
    'tools', ...
    'ardupilot', ...
    'windows', ...
    'Install-QGroundControl.ps1'));

verifyTrue(testCase, contains(missionPlannerText, 'Режим проверки'));
verifyTrue(testCase, contains(qgcText, 'Режим проверки'));
verifyTrue(testCase, contains(missionPlannerText, 'не выполнялась'));
verifyTrue(testCase, contains(qgcText, 'не выполнялась'));
end
