function tests = test_onekey_config
%TEST_ONEKEY_CONFIG Проверки конфигурации однокнопочного стенда TASK-14.
% Назначение:
%   Подтверждает наличие главного входного сценария, основного MATLAB-
%   исполнителя и обязательных полей конфигурации стенда.

tests = functiontests(localfunctions);
end

function setupOnce(~)
%SETUPONCE Подключить исходный код проекта.

repoRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(repoRoot);
addpath(fullfile(repoRoot, 'src'));
addpath(fullfile(repoRoot, 'scripts'));
end

function testDefaultStandConfigContainsRequiredFields(testCase)
%TESTDEFAULTSTANDCONFIGCONTAINSREQUIREDFIELDS Проверить состав конфигурации.

cfg = uav.setup.default_stand_config();

requiredFields = { ...
    'repo_root', ...
    'ardupilot_cfg', ...
    'execute_install', ...
    'execute_start', ...
    'execute_stop', ...
    'allow_ground_station_close', ...
    'prefer_ground_station', ...
    'ground_station_order', ...
    'launch_mission_planner', ...
    'launch_qgroundcontrol', ...
    'mavlink_udp_port', ...
    'json_udp_local_port', ...
    'json_udp_remote_port', ...
    'wsl_distro_name', ...
    'ardupilot_root', ...
    'matlab_wait_for_packet_script', ...
    'matlab_handshake_script', ...
    'matlab_full_stand_script', ...
    'matlab_ground_station_check_script', ...
    'powershell_install_mission_planner', ...
    'powershell_install_qgroundcontrol', ...
    'powershell_start_stand', ...
    'powershell_stop_stand', ...
    'powershell_test_stand', ...
    'wsl_setup_script', ...
    'wsl_start_sitl_script', ...
    'wsl_check_script', ...
    'log_check', ...
    'log_install', ...
    'log_start', ...
    'log_status', ...
    'log_full', ...
    'report_state', ...
    'report_summary', ...
    'notes'};

for idx = 1:numel(requiredFields)
    verifyTrue(testCase, isfield(cfg, requiredFields{idx}));
end

verifyFalse(testCase, cfg.execute_install);
verifyFalse(testCase, cfg.execute_start);
verifyFalse(testCase, cfg.execute_stop);
verifyFalse(testCase, cfg.allow_ground_station_close);
verifyGreaterThan(testCase, cfg.mavlink_udp_port, 0);
verifyGreaterThan(testCase, strlength(cfg.prefer_ground_station), 0);
end

function testOneKeyEntryPointsExist(testCase)
%TESTONEKEYENTRYPOINTSEXIST Проверить наличие входных файлов.

repoRoot = fileparts(fileparts(mfilename('fullpath')));

verifyTrue(testCase, isfile(fullfile(repoRoot, 'OneKeyArduPilotStand.m')));
verifyTrue(testCase, isfile(fullfile(repoRoot, 'scripts', 'onekey_ardupilot_stand.m')));
verifyTrue(testCase, isfile(fullfile(repoRoot, 'scripts', 'run_ardupilot_full_stand.m')));
verifyTrue(testCase, isfile(fullfile(repoRoot, 'scripts', 'check_ground_station_connection.m')));
end
