function tests = test_ardupilot_stand_scripts_presence
%TEST_ARDUPILOT_STAND_SCRIPTS_PRESENCE Проверки сценариев стенда TASK-14.
% Назначение:
%   Подтверждает наличие PowerShell- и Bash-сценариев однокнопочного
%   стенда, а также фиксирует безопасный режим запуска и остановки.

tests = functiontests(localfunctions);
end

function testStandScriptsExist(testCase)
%TESTSTANDSCRIPTSEXIST Проверить наличие файлов стенда.

repoRoot = fileparts(fileparts(mfilename('fullpath')));

expectedFiles = { ...
    fullfile(repoRoot, 'tools', 'ardupilot', 'windows', 'Start-ArduPilotStand.ps1'), ...
    fullfile(repoRoot, 'tools', 'ardupilot', 'windows', 'Stop-ArduPilotStand.ps1'), ...
    fullfile(repoRoot, 'tools', 'ardupilot', 'windows', 'Test-ArduPilotStand.ps1'), ...
    fullfile(repoRoot, 'tools', 'ardupilot', 'wsl', 'check_ardupilot_wsl.sh'), ...
    fullfile(repoRoot, 'tools', 'ardupilot', 'wsl', 'setup_ardupilot_wsl.sh'), ...
    fullfile(repoRoot, 'tools', 'ardupilot', 'wsl', 'start_arducopter_json_sitl.sh')};

for idx = 1:numel(expectedFiles)
    verifyTrue(testCase, isfile(expectedFiles{idx}));
end
end

function testStandScriptsExposeSafeMode(testCase)
%TESTSTANDSCRIPTSEXPOSESAFEMODE Проверить наличие параметров безопасного режима.

repoRoot = fileparts(fileparts(mfilename('fullpath')));

startText = fileread(fullfile( ...
    repoRoot, ...
    'tools', ...
    'ardupilot', ...
    'windows', ...
    'Start-ArduPilotStand.ps1'));
stopText = fileread(fullfile( ...
    repoRoot, ...
    'tools', ...
    'ardupilot', ...
    'windows', ...
    'Stop-ArduPilotStand.ps1'));
testText = fileread(fullfile( ...
    repoRoot, ...
    'tools', ...
    'ardupilot', ...
    'windows', ...
    'Test-ArduPilotStand.ps1'));
startWslText = fileread(fullfile( ...
    repoRoot, ...
    'tools', ...
    'ardupilot', ...
    'wsl', ...
    'start_arducopter_json_sitl.sh'));

verifyTrue(testCase, contains(startText, '[switch]$Execute'));
verifyTrue(testCase, contains(stopText, '[switch]$Execute'));
verifyTrue(testCase, contains(startText, '-LaunchMissionPlanner'));
verifyTrue(testCase, contains(startText, '-LaunchQGroundControl'));
verifyTrue(testCase, contains(testText, '14550'));
verifyTrue(testCase, contains(startWslText, '--model "JSON:${IP_ADDRESS}"'));
verifyTrue(testCase, contains(startWslText, '--out "udp:127.0.0.1:${MAVLINK_PORT}"'));
end
