function params = default_params_quad_x250()
%DEFAULT_PARAMS_QUAD_X250 Baseline demo parameters for a quad-X 250 mm UAV.
% Description:
%   Returns a compact parameter struct for a baseline quad-X 250 mm class
%   vehicle. Values are simple demo baselines, not identified hardware data.
%
% Inputs:
%   none
%
% Outputs:
%   params - parameter struct used by Stage-1 code
%
% Units:
%   SI only
%
% Assumptions:
%   The vehicle is symmetric, rigid, and intended only for baseline
%   demonstration and verification at this stage.

params = struct();

params.mass_kg = 1.00;
params.inertia_kgm2 = diag([5.0e-3, 5.0e-3, 9.0e-3]);
params.gravity_mps2 = 9.81;
params.env = struct();
params.env.mag_ned_uT = [20.0; 0.0; 45.0];

% wheelbase_m is the diagonal motor-to-motor distance for opposite rotors.
params.wheelbase_m = 0.25;
params.motor_radius_m = params.wheelbase_m / 2.0;

motor_xy_abs_m = params.motor_radius_m / sqrt(2.0);
params.motor_xy_m = [ ...
     motor_xy_abs_m, -motor_xy_abs_m; ...
     motor_xy_abs_m,  motor_xy_abs_m; ...
    -motor_xy_abs_m,  motor_xy_abs_m; ...
    -motor_xy_abs_m, -motor_xy_abs_m];

params.rotor = struct( ...
    'kT_N_per_radps2', 8.0e-6, ...
    'kQ_Nm_per_radps2', 1.2e-7);

params.kT_N_per_radps2 = params.rotor.kT_N_per_radps2;
params.kQ_Nm_per_radps2 = params.rotor.kQ_Nm_per_radps2;
params.spin_dir = [1.0; -1.0; 1.0; -1.0];

params.motor = struct( ...
    'tau_s', 0.05, ...
    'omega_min_radps', 0.0, ...
    'omega_max_radps', 900.0, ...
    'command_is_omega_ref', true);

params.rate_pid_gains = struct( ...
    'Kp', [0.10; 0.10; 0.08], ...
    'Ki', [0.02; 0.02; 0.01], ...
    'Kd', [0.002; 0.002; 0.001]);

params.sensors = struct();
params.sensors.imu = struct( ...
    'accel_bias_b_mps2', zeros(3, 1), ...
    'accel_noise_std_b_mps2', zeros(3, 1), ...
    'gyro_bias_b_radps', zeros(3, 1), ...
    'gyro_noise_std_b_radps', zeros(3, 1));
params.sensors.baro = struct( ...
    'alt_bias_m', 0.0, ...
    'alt_noise_std_m', 0.0);
params.sensors.gnss = struct( ...
    'pos_bias_ned_m', zeros(3, 1), ...
    'pos_noise_std_ned_m', zeros(3, 1), ...
    'vel_bias_ned_mps', zeros(3, 1), ...
    'vel_noise_std_ned_mps', zeros(3, 1));
params.sensors.mag = struct( ...
    'field_bias_b_uT', zeros(3, 1), ...
    'field_noise_std_b_uT', zeros(3, 1));

% Estimator baseline/demo gains:
%   k_acc and k_mag are complementary correction rates [1/s] for
%   accelerometer roll/pitch and magnetometer yaw channels.
%   k_baro is the altitude correction rate [1/s].
%   use_imu_prediction enables vertical prediction from IMU specific force.
%   vz_damping is a simple vertical-speed damping rate [1/s].
params.estimator = struct();
params.estimator.attitude = struct( ...
    'k_acc', 4.0, ...
    'k_mag', 2.0);
params.estimator.altitude = struct( ...
    'k_baro', 3.0, ...
    'use_imu_prediction', true, ...
    'vz_damping', 0.8);
params.hover_omega_radps = sqrt((params.mass_kg * params.gravity_mps2) / ...
    (4.0 * params.rotor.kT_N_per_radps2));
params.demo.t_final_s = 2.0;
params.demo.initial_state = [zeros(6, 1); 1.0; 0.0; 0.0; 0.0; zeros(3, 1)];
params.demo.dt_s = 0.01;
params.demo.motor_spool_t_final_s = 0.5;
params.demo.openloop_hover_t_final_s = 2.0;
params.demo.case_hover_t_final_s = 2.0;
params.demo.case_yaw_step_t_final_s = 2.0;
params.demo.yaw_step_time_s = 0.60;
params.demo.yaw_step_moment_Nm = 0.02;
params.demo.initial_state_plant = [params.demo.initial_state; zeros(4, 1)];
end
