%% MEASURE_ARDUPILOT_JSON_EXCHANGE_RATE Измерить частоту обмена после восстановления baseline.
% Назначение:
%   Повторно использует восстановленный 20-секундный обмен TASK-15 как
%   единственную допустимую базу для измерения частоты `ArduPilot JSON/UDP`.
%   Сначала запускает `run_ardupilot_task15_baseline_exchange.m`, затем
%   формирует компактный табличный и текстовый отчеты с частотами,
%   периодами и счетчиками обмена.
%
% Входы:
%   none
%
% Выходы:
%   task_17_exchange_rate_measurement - структура результата в базовом
%   рабочем пространстве MATLAB
%
% Единицы измерения:
%   время - секунды;
%   частота - герцы;
%   ШИМ - микросекунды;
%   команды частоты вращения винтов - рад/с
%
% Допущения:
%   Измерение частоты TASK-17 допустимо только при восстановленном
%   baseline-обмене TASK-15.

repo_root = fileparts(fileparts(mfilename('fullpath')));
reports_dir = fullfile(repo_root, 'artifacts', 'reports');
logs_dir = fullfile(repo_root, 'artifacts', 'logs');
baseline_script_path = fullfile(repo_root, 'scripts', 'run_ardupilot_task15_baseline_exchange.m');
summary_log_path = fullfile(logs_dir, 'task_17_exchange_rate_measurement.txt');
csv_report_path = fullfile(reports_dir, 'task_17_exchange_rate_measurement.csv');
mat_report_path = fullfile(reports_dir, 'task_17_exchange_rate_measurement.mat');

if ~isfolder(reports_dir)
    mkdir(reports_dir);
end

if ~isfolder(logs_dir)
    mkdir(logs_dir);
end

run(baseline_script_path);
baseline = evalin('base', 'task_17_task15_baseline_exchange');
metrics = baseline.metrics;

measurement = struct();
measurement.host_ip = string(baseline.cfg.udp_remote_ip);
measurement.launch_command = string(baseline.launch_command);
measurement.launch_pid = double(baseline.process_after_launch.pid);
measurement.process_alive_after_launch = logical(baseline.process_after_launch.is_alive);
measurement.process_alive_after_20s = logical(baseline.process_after_live.is_alive);
measurement.baseline_restored = logical(baseline.baseline_restored);
measurement.first_failure_reason = string(baseline.first_failure_reason);
measurement.metrics = metrics;
measurement.baseline = baseline;

save(mat_report_path, 'measurement');
writetable(local_make_measurement_table(measurement), csv_report_path);
local_write_utf8_text(summary_log_path, local_make_measurement_log(measurement));

assignin('base', 'task_17_exchange_rate_measurement', measurement);

fprintf('Измерение частоты обмена ArduPilot JSON/UDP\n');
fprintf('  baseline восстановлен            : %s\n', local_bool_text(measurement.baseline_restored));
fprintf('  valid_rx_count                   : %d\n', metrics.valid_rx_count);
fprintf('  json_tx_count                    : %d\n', metrics.json_tx_count);
fprintf('  response_tx_count                : %d\n', metrics.response_tx_count);
fprintf('  средняя частота valid_rx [Hz]    : %.4f\n', metrics.valid_rx_rate_hz);
fprintf('  средняя частота response_tx [Hz] : %.4f\n', metrics.response_tx_rate_hz);
fprintf('  p95 периода valid_rx [s]         : %.6f\n', metrics.valid_rx_period_p95_s);
fprintf('  p95 периода response_tx [s]      : %.6f\n', metrics.response_tx_period_p95_s);
fprintf('  last_frame_count                 : %d\n', metrics.last_frame_count);

if ~measurement.baseline_restored
    error( ...
        'uav:task17:measure_rate:BaselineNotRestored', ...
        'Baseline TASK-15 не восстановлен; измерение частоты TASK-17 непригодно. Причина: %s', ...
        measurement.first_failure_reason);
end

function table_value = local_make_measurement_table(measurement)
%LOCAL_MAKE_MEASUREMENT_TABLE Сформировать CSV-таблицу измерения частоты.

metrics = measurement.metrics;
table_value = table( ...
    measurement.host_ip, ...
    measurement.launch_command, ...
    measurement.launch_pid, ...
    measurement.process_alive_after_launch, ...
    measurement.process_alive_after_20s, ...
    measurement.baseline_restored, ...
    metrics.valid_rx_count, ...
    metrics.json_tx_count, ...
    metrics.response_tx_count, ...
    metrics.invalid_rx_count, ...
    metrics.udp_rx_datagram_count, ...
    metrics.valid_rx_rate_hz, ...
    metrics.json_tx_rate_hz, ...
    metrics.response_tx_rate_hz, ...
    metrics.valid_rx_period_mean_s, ...
    metrics.valid_rx_period_p95_s, ...
    metrics.response_tx_period_mean_s, ...
    metrics.response_tx_period_p95_s, ...
    metrics.model_step_elapsed_mean_s, ...
    metrics.json_encode_elapsed_mean_s, ...
    metrics.udp_read_elapsed_mean_s, ...
    metrics.udp_write_elapsed_mean_s, ...
    metrics.loop_elapsed_mean_s, ...
    metrics.frame_count_delta, ...
    metrics.last_frame_count, ...
    metrics.last_sender_address, ...
    metrics.last_sender_port, ...
    metrics.last_magic, ...
    string(local_format_vector(metrics.last_pwm_us)), ...
    string(local_format_vector(metrics.last_motor_cmd_radps)), ...
    metrics.quat_true_finite, ...
    metrics.quat_est_finite, ...
    string(metrics.last_exchange_status), ...
    string(measurement.first_failure_reason), ...
    'VariableNames', { ...
        'host_ip', ...
        'launch_command', ...
        'arducopter_pid', ...
        'process_alive_after_launch', ...
        'process_alive_after_20s', ...
        'baseline_restored', ...
        'valid_rx_count', ...
        'json_tx_count', ...
        'response_tx_count', ...
        'invalid_rx_count', ...
        'udp_rx_datagram_count', ...
        'valid_rx_rate_hz', ...
        'json_tx_rate_hz', ...
        'response_tx_rate_hz', ...
        'valid_rx_period_mean_s', ...
        'valid_rx_period_p95_s', ...
        'response_tx_period_mean_s', ...
        'response_tx_period_p95_s', ...
        'model_step_elapsed_mean_s', ...
        'json_encode_elapsed_mean_s', ...
        'udp_read_elapsed_mean_s', ...
        'udp_write_elapsed_mean_s', ...
        'loop_elapsed_mean_s', ...
        'frame_count_delta', ...
        'last_frame_count', ...
        'last_sender_address', ...
        'last_sender_port', ...
        'last_magic', ...
        'last_pwm_us', ...
        'last_motor_cmd_radps', ...
        'quat_true_finite', ...
        'quat_est_finite', ...
        'last_exchange_status', ...
        'first_failure_reason'});
end

function text_value = local_make_measurement_log(measurement)
%LOCAL_MAKE_MEASUREMENT_LOG Сформировать текстовый журнал измерения.

metrics = measurement.metrics;
lines = strings(0, 1);
lines(end + 1, 1) = "Измерение частоты обмена ArduPilot JSON/UDP";
lines(end + 1, 1) = "============================================================";
lines(end + 1, 1) = "Baseline TASK-15 восстановлен      : " + local_bool_text(measurement.baseline_restored);
lines(end + 1, 1) = "Адрес Windows-хоста для WSL2       : " + measurement.host_ip;
lines(end + 1, 1) = "Команда запуска ArduPilot          : " + measurement.launch_command;
lines(end + 1, 1) = "PID arducopter                     : " + string(measurement.launch_pid);
lines(end + 1, 1) = "Процесс жив после запуска          : " + local_bool_text(measurement.process_alive_after_launch);
lines(end + 1, 1) = "Процесс жив после 20 секунд        : " + local_bool_text(measurement.process_alive_after_20s);
lines(end + 1, 1) = "valid_rx_count                     : " + string(metrics.valid_rx_count);
lines(end + 1, 1) = "json_tx_count                      : " + string(metrics.json_tx_count);
lines(end + 1, 1) = "response_tx_count                  : " + string(metrics.response_tx_count);
lines(end + 1, 1) = "invalid_rx_count                   : " + string(metrics.invalid_rx_count);
lines(end + 1, 1) = "udp_rx_datagram_count              : " + string(metrics.udp_rx_datagram_count);
lines(end + 1, 1) = "Средняя частота valid_rx [Hz]      : " + sprintf('%.4f', metrics.valid_rx_rate_hz);
lines(end + 1, 1) = "Средняя частота json_tx [Hz]       : " + sprintf('%.4f', metrics.json_tx_rate_hz);
lines(end + 1, 1) = "Средняя частота response_tx [Hz]   : " + sprintf('%.4f', metrics.response_tx_rate_hz);
lines(end + 1, 1) = "Средний период valid_rx [s]        : " + sprintf('%.6f', metrics.valid_rx_period_mean_s);
lines(end + 1, 1) = "95-процентиль valid_rx [s]         : " + sprintf('%.6f', metrics.valid_rx_period_p95_s);
lines(end + 1, 1) = "Средний период response_tx [s]     : " + sprintf('%.6f', metrics.response_tx_period_mean_s);
lines(end + 1, 1) = "95-процентиль response_tx [s]      : " + sprintf('%.6f', metrics.response_tx_period_p95_s);
lines(end + 1, 1) = "Среднее время шага модели [s]      : " + sprintf('%.8f', metrics.model_step_elapsed_mean_s);
lines(end + 1, 1) = "Среднее время кодирования JSON [s] : " + sprintf('%.8f', metrics.json_encode_elapsed_mean_s);
lines(end + 1, 1) = "Среднее время чтения UDP [s]       : " + sprintf('%.8f', metrics.udp_read_elapsed_mean_s);
lines(end + 1, 1) = "Среднее время записи UDP [s]       : " + sprintf('%.8f', metrics.udp_write_elapsed_mean_s);
lines(end + 1, 1) = "Среднее время цикла MATLAB [s]     : " + sprintf('%.8f', metrics.loop_elapsed_mean_s);
lines(end + 1, 1) = "Прирост frame_count                : " + string(metrics.frame_count_delta);
lines(end + 1, 1) = "Последний frame_count              : " + string(metrics.last_frame_count);
lines(end + 1, 1) = "Последний sender address           : " + string(metrics.last_sender_address);
lines(end + 1, 1) = "Последний sender port              : " + string(metrics.last_sender_port);
lines(end + 1, 1) = "Последний magic                    : " + string(metrics.last_magic);
lines(end + 1, 1) = "Последние ШИМ [us]                 : [" + local_format_vector(metrics.last_pwm_us) + "]";
lines(end + 1, 1) = "Последние motor_cmd [rad/s]        : [" + local_format_vector(metrics.last_motor_cmd_radps) + "]";
lines(end + 1, 1) = "Норма истинного кватерниона конечна: " + local_bool_text(metrics.quat_true_finite);
lines(end + 1, 1) = "Норма оцененного кватерниона конечна: " + local_bool_text(metrics.quat_est_finite);
lines(end + 1, 1) = "Итоговый статус обмена             : " + string(metrics.last_exchange_status);
lines(end + 1, 1) = "Первая причина отказа              : " + string(measurement.first_failure_reason);
text_value = strjoin(lines, newline) + newline;
end

function text_value = local_format_vector(vec_value)
%LOCAL_FORMAT_VECTOR Сформировать компактную строку вектора.

text_value = strtrim(sprintf('%.6f ', double(vec_value(:))));
end

function text_value = local_bool_text(flag_value)
%LOCAL_BOOL_TEXT Преобразовать логический признак в русскую строку.

if flag_value
    text_value = "да";
else
    text_value = "нет";
end
end

function local_write_utf8_text(path_value, text_value)
%LOCAL_WRITE_UTF8_TEXT Сохранить текст UTF-8 без BOM.

folder_path = fileparts(path_value);
if ~isempty(folder_path) && ~isfolder(folder_path)
    mkdir(folder_path);
end

fid = fopen(path_value, 'w', 'n', 'UTF-8');
if fid < 0
    error( ...
        'uav:task17:measure_rate:OpenFile', ...
        'Не удалось открыть файл %s.', ...
        path_value);
end

cleanup_obj = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, '%s', char(text_value));
end
