function status_info = stand_status(cfg)
%STAND_STATUS Вернуть сводное состояние однокнопочного стенда.
% Назначение:
%   Объединяет результаты проверки Windows, WSL, наземных станций
%   управления, доступности UDP, требуемых сценариев и последних журналов.
%   Функция используется режимами check, status, install, start и full.
%
% Входы:
%   cfg - необязательная конфигурация стенда
%
% Выходы:
%   status_info - структура со сводным состоянием стенда
%
% Единицы измерения:
%   сетевые порты задаются целыми числами
%
% Допущения:
%   Отсутствие внешних средств фиксируется в сообщениях и не считается
%   аварийным завершением функции.

if nargin < 1 || isempty(cfg)
    cfg = uav.setup.default_stand_config();
end

status_info = struct();
status_info.cfg = cfg;
status_info.windows = uav.setup.check_windows_tools(cfg);
status_info.wsl = uav.setup.check_wsl_tools(cfg);
status_info.ground_stations = status_info.windows.ground_stations;
status_info.ardupilot = uav.ardupilot.inspect_sitl_environment(cfg.ardupilot_cfg);
status_info.udp = uav.ardupilot.json_udp_is_available();
status_info.scripts = local_script_presence(cfg);
status_info.latest_logs = local_collect_logs(cfg);
status_info.ports = local_port_status([ ...
    cfg.mavlink_udp_port; ...
    cfg.json_udp_local_port; ...
    cfg.json_udp_remote_port]);
status_info.processes = local_active_processes();

status_info.ready_for_install = status_info.windows.is_windows ...
    && status_info.windows.has_powershell ...
    && status_info.windows.wsl.is_available;
status_info.ready_for_start = status_info.wsl.is_ready ...
    && status_info.udp.is_available;

status_info.messages = [ ...
    status_info.windows.messages(:); ...
    status_info.wsl.messages(:); ...
    "UDP в MATLAB: " + local_bool_text(status_info.udp.is_available); ...
    "Сценарий ожидания первого пакета: " ...
    + local_bool_text(status_info.scripts.wait_for_packet_present); ...
    "Сценарий проверки обмена: " ...
    + local_bool_text(status_info.scripts.handshake_present); ...
    "Сценарий полного запуска стенда: " ...
    + local_bool_text(status_info.scripts.full_stand_present); ...
    "Сценарий проверки наземной станции: " ...
    + local_bool_text(status_info.scripts.ground_station_check_present); ...
    "PowerShell-установка Mission Planner: " ...
    + local_bool_text(status_info.scripts.install_mission_planner_present); ...
    "PowerShell-установка QGroundControl: " ...
    + local_bool_text(status_info.scripts.install_qgroundcontrol_present); ...
    "PowerShell-запуск стенда: " ...
    + local_bool_text(status_info.scripts.start_stand_present); ...
    "PowerShell-остановка стенда: " ...
    + local_bool_text(status_info.scripts.stop_stand_present); ...
    "PowerShell-проверка стенда: " ...
    + local_bool_text(status_info.scripts.test_stand_present); ...
    "Bash-проверка ArduPilot внутри WSL: " ...
    + local_bool_text(status_info.scripts.wsl_check_present); ...
    "Готовность к режиму install: " ...
    + local_bool_text(status_info.ready_for_install); ...
    "Готовность к режиму start: " ...
    + local_bool_text(status_info.ready_for_start)];
end

function scripts = local_script_presence(cfg)
%LOCAL_SCRIPT_PRESENCE Проверить наличие требуемых сценариев.

repo_root = char(cfg.repo_root);

scripts = struct();
scripts.wait_for_packet_present = isfile(fullfile( ...
    repo_root, ...
    char(cfg.matlab_wait_for_packet_script)));
scripts.handshake_present = isfile(fullfile( ...
    repo_root, ...
    char(cfg.matlab_handshake_script)));
scripts.full_stand_present = isfile(fullfile( ...
    repo_root, ...
    char(cfg.matlab_full_stand_script)));
scripts.ground_station_check_present = isfile(fullfile( ...
    repo_root, ...
    char(cfg.matlab_ground_station_check_script)));
scripts.install_mission_planner_present = isfile(fullfile( ...
    repo_root, ...
    char(cfg.powershell_install_mission_planner)));
scripts.install_qgroundcontrol_present = isfile(fullfile( ...
    repo_root, ...
    char(cfg.powershell_install_qgroundcontrol)));
scripts.start_stand_present = isfile(fullfile( ...
    repo_root, ...
    char(cfg.powershell_start_stand)));
scripts.stop_stand_present = isfile(fullfile( ...
    repo_root, ...
    char(cfg.powershell_stop_stand)));
scripts.test_stand_present = isfile(fullfile( ...
    repo_root, ...
    char(cfg.powershell_test_stand)));
scripts.wsl_check_present = isfile(fullfile( ...
    repo_root, ...
    char(cfg.wsl_check_script)));
end

function latest_logs = local_collect_logs(cfg)
%LOCAL_COLLECT_LOGS Собрать сведения о последних журналах.

log_fields = { ...
    'log_check', ...
    'log_install', ...
    'log_start', ...
    'log_status', ...
    'log_full', ...
    'log_install_mission_planner', ...
    'log_install_qgroundcontrol', ...
    'log_install_ardupilot_wsl', ...
    'log_start_stand', ...
    'log_wait_after_start', ...
    'log_handshake_after_start', ...
    'log_ground_station_check'};

latest_logs = repmat(struct( ...
    'name', "", ...
    'path', "", ...
    'exists', false, ...
    'timestamp', ""), numel(log_fields), 1);

for idx = 1:numel(log_fields)
    field_name = log_fields{idx};
    log_path = fullfile(char(cfg.repo_root), char(cfg.(field_name)));
    latest_logs(idx).name = string(field_name);
    latest_logs(idx).path = string(log_path);

    if isfile(log_path)
        file_info = dir(log_path);
        latest_logs(idx).exists = true;
        latest_logs(idx).timestamp = string(file_info.date);
    end
end
end

function ports = local_port_status(port_numbers)
%LOCAL_PORT_STATUS Проверить наличие слушателей или процессов на портах.

ports = struct();
ports.entries = repmat(struct('port', 0, 'is_busy', false, 'lines', strings(0, 1)), ...
    numel(port_numbers), 1);

[~, output] = system('netstat -ano -p udp');
output_lines = splitlines(string(output));

for idx = 1:numel(port_numbers)
    port_value = double(port_numbers(idx));
    token = ":" + string(port_value);
    matched = output_lines(contains(output_lines, token));
    matched = matched(strlength(strtrim(matched)) > 0);

    ports.entries(idx).port = port_value;
    ports.entries(idx).is_busy = ~isempty(matched);
    ports.entries(idx).lines = matched;
end
end

function processes = local_active_processes()
%LOCAL_ACTIVE_PROCESSES Вернуть сведения о связанных процессах.

processes = struct();
processes.ardupilot_related = strings(0, 1);

if ~ispc
    return;
end

[~, output] = system('tasklist /FO CSV /NH');
lines = splitlines(string(output));
lines = lines(strlength(strtrim(lines)) > 0);

mask = contains(lower(lines), "qgroundcontrol.exe") ...
    | contains(lower(lines), "missionplanner.exe") ...
    | contains(lower(lines), "wsl.exe") ...
    | contains(lower(lines), "python.exe") ...
    | contains(lower(lines), "mavproxy.exe");

processes.ardupilot_related = lines(mask);
end

function text_value = local_bool_text(flag_value)
%LOCAL_BOOL_TEXT Преобразовать логический признак в строку.

if flag_value
    text_value = "да";
else
    text_value = "нет";
end
end
