function stop_existing_sitl(distro_name, host_ip, mavlink_port)
%STOP_EXISTING_SITL Остановить процессы стенда ArduPilot текущего прогона.
% Назначение:
%   Завершает экземпляры `arducopter`, `sim_vehicle.py`, `MAVProxy` и
%   вспомогательные процессы `wsl.exe`, относящиеся к текущему стенду,
%   чтобы новый прогон не наследовал занятые порты и старые журналы.
%
% Входы:
%   distro_name  - имя дистрибутива WSL
%   host_ip      - IP адрес Windows-хоста, используемый текущим стендом
%   mavlink_port - порт потока MAVLink к наземной станции управления
%
% Выходы:
%   none
%
% Единицы измерения:
%   mavlink_port - целое число порта UDP
%
% Допущения:
%   Завершаются только процессы, совпадающие по имени и/или параметрам
%   запуска с текущим стендом сопряжения ArduPilot.

host_ip = char(string(host_ip));
kill_wsl_command = sprintf([ ...
    'wsl -d %s -- bash -lc "', ...
    'pkill -f ''build/sitl/bin/arducopter'' >/dev/null 2>&1 || true; ', ...
    'pkill -f ''sim_vehicle.py'' >/dev/null 2>&1 || true; ', ...
    'pkill -f ''MAVProxy'' >/dev/null 2>&1 || true; ', ...
    'pkill -f ''python.*pymavlink'' >/dev/null 2>&1 || true; ', ...
    'if command -v fuser >/dev/null 2>&1; then ', ...
    'fuser -k 5760/tcp 5762/tcp 5763/tcp >/dev/null 2>&1 || true; ', ...
    'fi"'], ...
    char(string(distro_name)));
system(kill_wsl_command);

kill_win_command = sprintf([ ...
    'powershell -NoProfile -NonInteractive -Command ', ...
    '"$ports = @(5760,5762,5763,%d); ', ...
    '$procNames = @(''wsl'',''wslhost'',''python'',''python3'',''MAVProxy''); ', ...
    '$conns = Get-NetTCPConnection -State Listen -ErrorAction SilentlyContinue | Where-Object { $ports -contains $_.LocalPort }; ', ...
    'foreach ($conn in $conns) { ', ...
    '$p = Get-Process -Id $conn.OwningProcess -ErrorAction SilentlyContinue; ', ...
    'if ($null -ne $p -and $procNames -contains $p.ProcessName) { Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue; } ', ...
    '} ', ...
    'Get-CimInstance Win32_Process | ', ...
    'Where-Object { ', ...
    '(($_.Name -ieq ''wsl.exe'') -or ($_.Name -ieq ''python.exe'')) -and ', ...
    '(($_.CommandLine -like ''*%s*'') -or ($_.CommandLine -like ''*%d*'') -or ($_.CommandLine -like ''*5762*'') -or ($_.CommandLine -like ''*5763*'')) ', ...
    '} | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }"'], ...
    double(mavlink_port), ...
    host_ip, ...
    double(mavlink_port));
system(kill_win_command);
pause(2.0);
end
