function stop_existing_sitl(distro_name, host_ip, mavlink_port)
%STOP_EXISTING_SITL Остановить процессы стенда ArduPilot текущего прогона.
% Назначение:
%   Завершает экземпляры `arducopter`, `sim_vehicle.py`, `MAVProxy` и
%   вспомогательные процессы `wsl.exe`, относящиеся к текущему стенду,
%   чтобы новый прогон не наследовал занятые порты и старые журналы.
%
% Входы:
%   distro_name  - имя дистрибутива WSL
%   host_ip      - IP адрес Windows-хоста, используемый текущим стендом
%   mavlink_port - порт потока MAVLink к наземной станции управления
%
% Выходы:
%   none
%
% Единицы измерения:
%   mavlink_port - целое число порта UDP
%
% Допущения:
%   Завершаются только процессы, совпадающие по имени и/или параметрам
%   запуска с текущим стендом сопряжения ArduPilot.

host_ip = char(string(host_ip));
kill_wsl_command = sprintf([ ...
    'wsl -d %s -- bash -lc ', ...
    '"pkill -f ''arducopter.*%s'' >/dev/null 2>&1 || true; ', ...
    'pkill -f ''sim_vehicle.py.*%s'' >/dev/null 2>&1 || true; ', ...
    'pkill -f ''MAVProxy'' >/dev/null 2>&1 || true"'], ...
    char(string(distro_name)), ...
    host_ip, ...
    host_ip);
system(kill_wsl_command);

kill_win_command = sprintf([ ...
    'powershell -NoProfile -NonInteractive -Command ', ...
    '"Get-CimInstance Win32_Process | ', ...
    'Where-Object { ', ...
    '($_.Name -ieq ''wsl.exe'') -and ', ...
    '(($_.CommandLine -like ''*%s*'') -or ($_.CommandLine -like ''*%d*'')) ', ...
    '} | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }"'], ...
    host_ip, ...
    double(mavlink_port));
system(kill_win_command);
end
